export const getCompletedSteps = state => state.registration.get('completedSteps')
export const getActiveStep = state => state.registration.get('activeStep')
export const getEmail = state => state.registration.get('email')
export const getUsername = state => state.registration.get('username')
export const getPassword = state => state.registration.get('password')
export const getRepeatPassword = state => state.registration.get('repeatPassword')
export const getSelectedDuration = state => state.registration.get('selectedDuration')
export const getSelectedSunscription = state => state.registration.get('selectedSubscription')
