export { default as ProfileLayout } from 'universal/layouts/ProfileLayout'
export { default as ProfileHomeLayout } from 'universal/layouts/ProfileHomeLayout'
export { default as ProfileStudentsLayout } from 'universal/layouts/ProfileStudentsLayout'
export { default as ProfileCalendarLayout } from 'universal/layouts/ProfileCalendarLayout'
export { default as ProfileInvoicesLayout } from 'universal/layouts/ProfileInvoicesLayout'
export { default as ProfileStatisticsLayout } from 'universal/layouts/ProfileStatisticsLayout'
export { default as ProfileNotificationsLayout } from 'universal/layouts/ProfileNotificationsLayout'


export { default as SiteLayout } from 'universal/layouts/SiteLayout'
export { default as SiteHomeLayout } from 'universal/layouts/SiteHomeLayout'
export { default as SiteFeaturesLayout } from 'universal/layouts/SiteFeaturesLayout'
export { default as SitePricingLayout } from 'universal/layouts/SitePricingLayout'
export { default as SiteContactsLayout } from 'universal/layouts/SiteContactsLayout'
export { default as SiteLoginLayout } from 'universal/layouts/SiteLoginLayout'
export { default as SiteRegistrationLayout } from 'universal/layouts/SiteRegistrationLayout'
export { default as NotFoundLayout } from 'universal/layouts/NotFoundLayout'
